apiVersion: v1
kind: Service
metadata:
  name: cloud-project-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  labels:
    app: cloud-project
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: cloud-project
  sessionAffinity: None
