apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-project-deployment
  labels:
    app: cloud-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-project
  template:
    metadata:
      labels:
        app: cloud-project
    spec:
      containers:
      - name: static-site
        image: avdonr/cloud-project:website
        imagePullPolicy: Always
        resources:
        ports:
        - containerPort: 3000
      - name: server
        image: avdonr/cloud-project:server
        imagePullPolicy: Always
        resources:
        ports:
        - containerPort: 4000
      - name: database
        image: avdonr/cloud-project:database
        imagePullPolicy: Always
        resources:
        ports:
        - containerPort: 4001